micronaut:
  application:
    name: grpcStockQuotationsProvider
grpc:
  server:
    port: 50052
    client:
      plaintext: true
      max-retry-attempts: 10
  channels:
    stock-data-hub:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10
